# Site settings
#title: "Telectric | Blog de tecnología"
title: "Jazztel/Orange"
#email: info@telectric.es
lema: Ingeniería, Instalaciones e Integración
description: "Un equipo de Ingenieros Técnicos de Telecomunicaciones e Industriales, nuestros expertos Integradores de servicios junto con unos experimentados Instaladores autorizados nos permienten afrontar los retos que nos planteen sus problemas para encontrar las mejores soluciones."
baseurl: ""
url: ""
twitter_username: telectric_es
#github_username:  telectric
# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
#redcarpet
#kramdown
#permalink: pretty
