# Site settings
title: "Telectric: Blog de Redes y Sistemas"
#email: info@telectric.es
lema: Ingeniería, Instalaciones e Integración
description: "Un equipo de Ingenieros Técnicos de Telecomunicaciones e Industriales, Integradores de servicios junto con nuestros Instaladores autorizados a su servicio."
baseurl: ""
url: ""
twitter_username: telectric_es
#github_username:  telectric
# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
#redcarpet
#kramdown
#permalink: pretty
